### ISSUE TITLE
% in hashtags

### ISSUE THREAD

**Issue by lavie** [Bitcoin-FUD/btcfudbuster#4]
https://github.com/Bitcoin-FUD/btcfudbuster/blob/ddaab1aa8a52f9bfe4ce9de67c0a08b2bd3b85ba/material/attacks/51-percent.toml#L1

I think you can't have `%` in hashtags, so some of these tags should probably be revised. e.g. `51attack`

**Comment by Czino** [comment]
Yes, good point, that's right. I added two commits in regards to this

Removing % symbol
https://github.com/Bitcoin-FUD/btcfudbuster/pull/3/commits/0a6f2750d3b50da547cb0e6fd79b35935d876c66

Adding % symbol back because although twitter won't recognize it as a hashtag, the bot will still do, so we should allow for this case still
https://github.com/Bitcoin-FUD/btcfudbuster/pull/3/commits/46d68168b47e5f07fc9f2b1d02e4f3784ae986da
